name: Build CI

on:
  push:
    branches: [main, deploy-ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn run test
        env:
          CI: true
      - name: Generate build
        run: yarn run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: react-flexile-build
          path: build
