name: Build & Deploy CI

on:
  push:
    branches: [main, docker-ci]
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.css'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn run test
        env:
          CI: true
      - name: Generate build
        run: yarn run build
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: react-flexile-build.zip
          path: build
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: react-flexile-build.zip
          path: react-flexile-build.zip

  # deploy-to-server:
  #   name: Deploy to server
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #     - shell: bash
  #       run: |
  #         rm -rfv /var/www/html/*
  #     - name: Download build
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: react-flexile-build
  #         path: /var/www/html

  build-docker:
    name: Build the Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build ./server --file Dockerfile --tag $GITHUB_REPOSITORY
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flexile-react:latest